version: 2.1
orbs:
  architect: giantswarm/architect@4.29.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      # Build chart and push to catalogs.
      - architect/push-to-app-catalog:
          context: "architect"
          name: push-starboard-app-to-control-plane-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "starboard-app"
          executor: "app-build-suite"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: push-starboard-app-to-giantswarm-catalog
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "starboard-app"
          executor: "app-build-suite"
          persist_chart_archive: true
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: execute chart tests
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - push-starboard-app-to-giantswarm-catalog

      # Push starboard to collections.
      - architect/push-to-app-collection:
          name: aws-app-collection
          context: "architect"
          app_name: "starboard-app"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-starboard-app-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: azure-app-collection
          context: "architect"
          app_name: "starboard-app"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-starboard-app-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      #- architect/push-to-app-collection:
      #    name: kvm-app-collection
      #    context: "architect"
      #    app_name: "starboard-app"
      #    app_collection_repo: "kvm-app-collection"
      #    requires:
      #      - push-starboard-app-to-control-plane-catalog
      #    filters:
      #      branches:
      #        ignore: /.*/
      #      tags:
      #        only: /^v.*/

#       - architect/push-to-app-collection:
#           name: vmware-app-collection
#           context: "architect"
#           app_name: "starboard-app"
#           app_collection_repo: "vmware-app-collection"
#           requires:
#             - push-starboard-app-to-control-plane-catalog
#           filters:
#             branches:
#               ignore: /.*/
#             tags:
#               only: /^v.*/


      - architect/push-to-app-collection:
          context: architect
          name: push-to-cloud-director-app-collection
          app_name: "starboard-app"
          app_collection_repo: "cloud-director-app-collection"
          requires:
            - push-starboard-app-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/


      - architect/push-to-app-collection:
          context: architect
          name: push-to-capa-app-collection
          app_name: "starboard-app"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-starboard-app-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

