# We install CRDs through a Job with the helm specific crd folder.
crds:
  image:
    tag: 1.23.6
  install: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Upstream offers compliance specs which can be optionally installed.
specs:
  image:
    tag: 1.23.6
  install: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# managedBy is similar to .Release.Service but allows to overwrite the value
managedBy: Helm

image:
  registry: "docker.io"

# Security contexts for CRD and spec installs.
# Pod securityContext
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10000  # UID of `starboard` user from upstream
  runAsGroup: 10000  # UID of `starboard` user from upstream
  seccompProfile:
    type: RuntimeDefault

# Container securityContext
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10000  # UID of `starboard` user from upstream.
  runAsGroup: 10000  # UID of `starboard` user from upstream
  seccompProfile:
    type: RuntimeDefault

starboard-app:

  operator:
    # Reports are automatically deleted after this duration, causing a re-scan. Empty = never delete.
    vulnerabilityScannerReportTTL: "168h"  # 7 days
    # Generate reports for only the currently-deployed version of a replicaset.
    vulnerabilityScannerScanOnlyCurrentRevisions: true
    # scanJobsConcurrentLimit the maximum number of scan jobs create by the operator
    scanJobsConcurrentLimit: 10
    # scanJobsRetryDelay the duration to wait before retrying a failed scan job
    scanJobsRetryDelay: 30s

  image:
    repository: "docker.io/giantswarm/starboard-operator"

  rbac:
    pspEnabled: true

  targetNamespaces: ""

  # Pod securityContext
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 10000  # UID of `starboard` user from upstream.
    runAsGroup: 10000  # UID of `starboard` user from upstream
    seccompProfile:
      type: RuntimeDefault

  # Container securityContext
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 10000  # UID of `starboard` user from upstream.
    runAsGroup: 10000  # UID of `starboard` user from upstream
    seccompProfile:
      type: RuntimeDefault

  serviceAccount:
    # We set the service account name so that we can use it in our FlowSchema.
    name: "starboard-app"

  trivy:
    # Ideally, we use the in-cluster Trivy deployed from https://github.com/giantswarm/trivy-app
    # We also set the image here so that starboard can be deployed "standalone",
    # but this image is not used if using in-cluster Trivy.
    # Change or remove the `mode:` setting to let starboard pull its own Trivy images.
    imageRef: docker.io/giantswarm/trivy:0.24.0
    mode: ClientServer
    serverURL: "http://trivy-app:4954"
    # Resources for Trivy pods created by Starboard
    resources:
      requests:
        cpu: 100m
        memory: 100M
      limits:
        cpu: 500m
        memory: 1G

  kubeBench:
    imageRef: docker.io/giantswarm/kube-bench:0.6.3

  polaris:
    imageRef: docker.io/giantswarm/polaris:4.0

  conftest:
    imageRef: docker.io/giantswarm/conftest:v0.25.0

  aqua:
    imageRef: giantswarm/scanner:5.3
