# Values can be found here https://github.com/aquasecurity/starboard/blob/v0.11.0/deploy/helm/values.yaml

starboard-app:

  targetNamespaces: ""

  image:
    repository: "quay.io/giantswarm/starboard-operator"

  trivy:
    imageRef: quay.io/giantswarm/trivy:0.19.2
    mode: ClientServer
    serverURL: "https://trivy-app:4954"

  kubeBench:
    imageRef: quay.io/giantswarm/kube-bench:0.6.3

  polaris:
    imageRef: quay.io/giantswarm/polaris:4.0

  conftest:
    imageRef: giantswarm/conftest:v0.25.0

  aqua:
    imageRef: giantswarm/scanner:5.3
