apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
kind: FlowSchema
metadata:
  name: starboard
spec:
  priorityLevelConfiguration:
    name: starboard
  distinguisherMethod:
    type: ByUser
  rules:
  - resourceRules:
    clusterScope: true
    # - apiGroups: [""]
    #   namespaces: ["*"]
    #   resources: ["pods"]
    #   verbs: ["list", "get"]
    - apiGroups:
        - ""
      resources:
        - pods
        - pods/log
        - replicationcontrollers
        - services
        - resourcequotas
        - limitranges
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - ""
      resources:
        - nodes
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - ""
      resources:
        - configmaps
        - secrets
        - serviceaccounts
      verbs:
        - list
        - watch
        - get
        - create
        - update
    - apiGroups:
        - ""
      resources:
        - secrets
      verbs:
        - delete
    - apiGroups:
        - ""
      resources:
        - events
      verbs:
        - create
    - apiGroups:
        - apps
      resources:
        - replicasets
        - statefulsets
        - daemonsets
        - deployments
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - batch
      resources:
        - jobs
        - cronjobs
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - rbac.authorization.k8s.io
      resources:
        - roles
        - rolebindings
        - clusterroles
        - clusterrolebindings
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - apiextensions.k8s.io
      resources:
        - customresourcedefinitions
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - batch
      resources:
        - jobs
      verbs:
        - create
        - delete
    - apiGroups:
        - networking.k8s.io
      resources:
        - networkpolicies
        - ingresses
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - policy
      resources:
        - podsecuritypolicies
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - aquasecurity.github.io
      resources:
        - vulnerabilityreports
        - configauditreports
        - clusterconfigauditreports
        - ciskubebenchreports
        - clustercompliancereports
        - clustercompliancedetailreports
      verbs:
        - get
        - list
        - watch
        - create
        - update
        - delete
    - apiGroups:
        - aquasecurity.github.io
      resources:
        - clustercompliancereports/status
      verbs:
        - update
    subjects:
    - kind: ServiceAccount
      serviceAccount:
        name: {{ index .Values "starboard-app" "serviceAccount" "name" }}
        namespace: {{ .Release.Namespace }}
        clusterScope: true
