apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
kind: FlowSchema
metadata:
  name: starboard
spec:
  priorityLevelConfiguration:
    name: starboard
  distinguisherMethod:
    type: ByUser
  rules:
  - resourceRules:
    - apiGroups: [""]
      namespaces: ["demo"]
      resources: ["pods"]
      verbs: ["list", "get"]
    subjects:
    - kind: ServiceAccount
      serviceAccount:
        name: {{ index .Values "starboard-app" "serviceAccount" "name" }}
        namespace: {{ .Release.Namespace }}
        clusterScope: true
