apiVersion: flowcontrol.apiserver.k8s.io/v1alpha1
kind: PriorityLevelConfiguration
metadata:
  name: starboard
spec:
  type: Limited
  limited:
    assuredConcurrencyShares: 5
    limitResponse:
      queuing:
        # We estimate 4 calls per Job: create the Job, get the logs, store the report, delete the job.
        # Allow 4 x the configured number of concurrent jobs, up to 100 max because
        # we suspect report storage is a large request and we don't want to fill the API server memory.
        queueLengthLimit: {{ min (mul (index .Values "starboard-app" "operator" "scanJobsConcurrentLimit") 4) 100 }}
      type: Queue
